name: CI-Tag
on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    name: CI-Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Tag
        uses: neverendingqs/gh-action-tag-on-npm-version@v1.0.1
