name: CI-Tag
on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    name: CI-Tag

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Tag
        uses: TheKitoInc/gh-action-tag-on-npm-version@test
