name: CI
on: [push, pull_request]
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npm ci --ignore-scripts
      - run: npm run linter:ci
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", "current"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci --ignore-scripts
      - run: npm run test:ci
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npm ci --ignore-scripts
      - run: npm run build:ci
      - run: cp LICENSE dist/LICENSE
      - run: cp README.md dist/README.md
      - run: jq 'del(.devDependencies) | del(.scripts)' package.json > dist/package.json
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
